services:
  app:
    image: ghcr.io/flo0807/share-a-secret:latest@sha256:fe768c4950b84036ddd5d234944d484c5f23c1b24f1d6f4d9ffdb1bc5ba85e5c
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://postgres:postgres@database/postgres"
      SECRET_KEY_BASE: "fxcNnRdiwtsVvjYxPb1XDeL5fLqQdNP7XkILChPq0TODPAnv+8mPet56WfICmlv5"
      PHX_HOST: "localhost"
      PORT: 4000
    depends_on:
      - database
  database:
    image: postgres:latest@sha256:689da611f990d0698669f0a949fb870197a283ce1f7944895318a088a5d134c5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_data:
